### ISSUE TITLE
Different positions of switches

### ISSUE THREAD

**Issue by ashton** [Bastardkb/Dactyl-Manuform-PCB-Plate#2]
Hi @bstiq, first of all I'm huge fan of your work! Not sure if this is an issue but it's the only place that I can reach you, so sorry in advance if this is misplaced.

I have done a dactyl manuform mini based on your [personal repo](https://github.com/bstiq/dactyl-manuform-mini-keyboard), and it is awesome! I tried to organize a little bit the mess of wires due to handwiring, and I tought that this PCB would be a great way to do it. You say in the description that is compatible with dactyl manuform mini, in fact, if I'm not mistaken the thumb cluster pcb only works with mini. But after printing it and trying to build it, looks like that some of the switch positions are misplaced with the switch holes in the case, the stagger in the pinky and ring columns seems to be greater in the case than in the PCB and the spacing between the columns is different too. I don't have a lot of knowledge in Kicad but is there a way of fixing this? Is there a way of generate a pcb that would work well with my case?

Sorry for asking this here, and thanks in advance for the help!

**Comment by bstiq** [comment]
Hi,

Thanks !
The thumb cluster is only compatible with certain types of dactyls.
It's compatible with all my keyboards, and _should be_ with the og dactyl manuform mini:
https://github.com/l4u/dactyl-manuform-mini-keyboard

You can either use a different case model, or modify the PCB like you mentioned.
There's no way to generate it, you will need to change the edge cuts and position of the switches so it fits better (I recommend 3d printing tests), then handwiring everything.

It's quite a big project and I wouldn't recommend it if you don't have a lot of experience with PCB design.

If you want to go ahead or have questions about that, a better place to chat is on the bastardkb discord.
bastardkb.com/discord

Regards,
